### ISSUE TITLE
La vida de los personajes no baja del todo

### ISSUE THREAD

**Issue by martarc2001** [MooncakeStudio/Gridmoire-The-Fall-of-Sunhelm#62]
- La barra de vida de los personajes está vacía pero aún se puede atacar con ellos.
- También pasa con los enemigos.

**Comment by AlrekVikahrr** [comment]
Cuando queda muy poca vida, parece que la barra está vacía pero claramente se ve que sigue habiendo un fragmento de esta. Es el mismo efecto que cuando un pokémon queda a 1 ps, se ve de la misma manera.
